# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Word Character Count DotNet - Build and Test

on:
    push:
        branches: ["main"]
        paths:
            - "WordCharacterCountFunction/DotNet/**"
    pull_request:
        branches: ["main"]
        paths:
            - "WordCharacterCountFunction/DotNet/**"
    workflow_dispatch:

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup .NET
              uses: actions/setup-dotnet@v3

            - name: Restore dependencies
              working-directory: WordCharacterCountFunction/DotNet
              run: dotnet restore

            - name: Build
              working-directory: WordCharacterCountFunction/DotNet
              run: dotnet build --no-restore

            - name: Test
              working-directory: WordCharacterCountFunction/DotNet
              run: dotnet test --no-build --verbosity normal
